[package]
name = "host-rvl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
host-core = { path = "../host-core" }
rvl = { git = "https://github.com/cmdrvl/rvl.git", tag = "v0.5.1" }
serde.workspace = true
tokio.workspace = true
axum.workspace = true
